### PR TITLE
Create new popfinder release

### PR DESCRIPTION
**Pull request by katieb1**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by katieb1** [comment]
@conda-forge-admin, please add user @katieb1

**Comment by katieb1** [comment]
@conda-forge/core I am the maintainer, but have no write access. Can you give me write access?

**Comment by ocefpaf** [comment]
I send the team update command in https://github.com/conda-forge/popfinder-feedstock/issues/3

Please check your email (maybe spam) for the feedstock team invite. You should've got one before BTW, probably got lost in the spam folder.

**Comment by katieb1** [comment]
Great, thanks! Yes, I thought I should have gotten one before but couldn't find one in my inbox or spam folder. Must have deleted it by accident.

**Pull request merged**
